# Generated by Django 4.2.5 on 2024-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_pedido_delete_product_cart_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pedido",
        ),
        migrations.AddField(
            model_name="cart",
            name="pedido",
            field=models.ManyToManyField(to="cart.pedido"),
        ),
    ]
