# Generated by Django 4.2.5 on 2024-10-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item", "0003_alter_item_image"),
        ("cart", "0003_cart_created_at_remove_cart_pedido_cart_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="item",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="owner",
        ),
        migrations.AddField(
            model_name="cart",
            name="pedido",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cart.pedido"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="item.item"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
